# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_buddy_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='request',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='request',
            name='matched_request',
            field=models.ManyToManyField(related_name='_request_matched_request_+', to='gym_buddy_app.Request'),
        ),
        migrations.AddField(
            model_name='request',
            name='recommend_request',
            field=models.ManyToManyField(related_name='_request_recommend_request_+', to='gym_buddy_app.Request'),
        ),
        migrations.AddField(
            model_name='request',
            name='training_part',
            field=models.CharField(choices=[('L', 'Leg'), ('A', 'Arm'), ('C', 'Chest')], default='L', max_length=1),
        ),
        migrations.AddField(
            model_name='request',
            name='training_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='user_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='user_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='user_phone_number',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
